services:
  mysql:
    image: mysql:8.3
    container_name: mealbox-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mealbox
      MYSQL_USER: mealboxuser
      MYSQL_PASSWORD: mealboxpass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
